// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSaveController from "./auto_save_controller"
application.register("auto-save", AutoSaveController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import ColorPickerController from "./color_picker_controller"
application.register("color-picker", ColorPickerController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import DockController from "./dock_controller"
application.register("dock", DockController)

import EnableFieldController from "./enable_field_controller"
application.register("enable-field", EnableFieldController)

import FilePreviewController from "./file_preview_controller"
application.register("file-preview", FilePreviewController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HeadbarController from "./headbar_controller"
application.register("headbar", HeadbarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import SelectAllController from "./select_all_controller"
application.register("select-all", SelectAllController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
